[package]
name = "data-transformer-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1"
handlebars = "6"
handlebars_misc_helpers = "0.17"
tera = "1"

[dev-dependencies]
criterion2 = "2"

[[bench]]
name = "transform_benchmark"
harness = false
