[package]
name = "data-transformer-bench"
version = "0.2.0"
edition = "2021"

[dependencies]
handlebars = "6"
handlebars_misc_helpers = { version = "0.17", default-features = false, features = ["json", "string", "uuid"]}
serde_json = "1"
tera = "1"
vrl = "0.20"
rhai = {version = "1.20", features = ["serde"]}
mlua = { version = "0.9", features = ["lua54", "serialize"] }

[dev-dependencies]
criterion2 = "2"
pretty_assertions = "1"

[[bench]]
name = "transform_benchmark"
harness = false
